In [1]:
5+5

10

In [24]:
for i in range(1,5):
    for j in range(1,i+1):
        print("*",end=" ")
    print( )

* 
* * 
* * * 
* * * * 


In [25]:
str1='virat'
x=len(str1)
print(x)

5


In [28]:
for i in range(0,4):
    for j in range(0,4):
        if(i+j>=3):
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print( )

      * 
    * * 
  * * * 
* * * * 


In [36]:
inp=input("enter the name:")
for i in range(len(inp)):
    for j in range(0,i+1):
        print(inp[i],end=" ")
    print( )

enter the name:virat
v 
i i 
r r r 
a a a a 
t t t t t 


In [41]:
rec={}
n=int(input("enter the number of student"))
i=1
while i<=n:
    name=input("enter student name:")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
print("name of the student","% of marks")
for x in rec:
    print("\t",x,"\t\t",rec[x])

enter the number of student2
enter student name:abc
enter % marks of student98
enter student name:def
enter % marks of student89
name of the student % of marks
	 abc 		 98
	 def 		 89


In [43]:
d={1:'abc',2:'def',3:'ghi'}
print(d)

{1: 'abc', 2: 'def', 3: 'ghi'}


In [44]:
d[1]

'abc'

In [47]:
len(d)

3

In [51]:
del d[2]

In [52]:
print(d)

{1: 'abc', 3: 'ghi'}


In [54]:
d.clear()

In [55]:
print(d)

{}


In [58]:
word=input("enter any word:")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter any word:amitha
a occure 2 times
m occure 1 times
i occure 1 times
t occure 1 times
h occure 1 times


In [59]:
word=input("enter any word")
d={}
vowels={'a','e','i','o','u'}
for x in word:
    if x in vowels:
        d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occures",v,"times")
        

enter any wordamitha
a occures 2 times
i occures 1 times


In [60]:
n=[1,2,3,4,2,5,5,5,5]
print(n.count(5))

4


In [61]:
print(n.index(5))

5


In [62]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


In [65]:
n=[1,2,3,4,5]
x=n.pop(1)
print(n)
print(x)

[1, 3, 4, 5]
2


In [72]:
n=[1,2,3,4,5]
for i in range(len(n)):
    print(n[i])

1
2
3
4
5


In [73]:
n=[1,2,3,4,5]
x=n[:4]
print(x)

[1, 2, 3, 4]


In [74]:
n=[1,2,3,4,5]
x=n[::-1]
print(x)

[5, 4, 3, 2, 1]


In [75]:
n=[1,2,3,4,5]
n.pop()
print(n)

[1, 2, 3, 4]


In [76]:
n=[1,2,3,4,5]
n.reverse()
print(n)

[5, 4, 3, 2, 1]


In [77]:
n=['ammu','roshu','disha','gahu','nishi']
n.sort()
print(n)

['ammu', 'disha', 'gahu', 'nishi', 'roshu']


In [78]:
n=['ammu',37,'roshu',40,'disha','gahu',15,'nishi']
n.sort()
print(n)

TypeError: '<' not supported between instances of 'int' and 'str'

In [79]:
n=['ammu','roshu','disha','gahu','nishi']
n.sort(reverse=True)
print(n)

['roshu', 'nishi', 'gahu', 'disha', 'ammu']


In [80]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [81]:
n=['ammu','roshu','disha','gahu','nishi']
n[1]=8
print(n)

['ammu', 8, 'disha', 'gahu', 'nishi']


In [82]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [84]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [85]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [86]:
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [87]:
x=["MITE","Mangalore","NITTE"]
y=["MITE","Mangalore","NITTE"]
x==y
x!=y
z=["MITE","Mangalore","NITTE"]
x==z

True

In [89]:
m=[10,20,30,40,[50,60,70]]
m[3]
m[4][1]
m.clear()

In [90]:
n=[1,2,3,4]
print(4 in n)

True


In [91]:
n=[1,2,3,4]
print(5 in n)

False


In [93]:
words=["Mite","Mysore","Amitha"]
l=[w[0] for w in words]
print(l)

['M', 'M', 'A']


In [98]:
def time2(var):
    return var*2
#lambda var:var*2
seq=[1,2,3,4,5]
list(map(time2,seq))    

[2, 4, 6, 8, 10]

In [100]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))    
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [101]:
seq=[1,2,3,4,5]   
list(filter(lambda var:var%2==0,seq))

[2, 4]

In [104]:
import numpy as np
my_list=[1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [105]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [108]:
np.zeros(3)

array([0., 0., 0.])

In [110]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [112]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [114]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [115]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [116]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
np.random.rand(2)

array([0.00284305, 0.37819742])

In [119]:
np.random.rand(5,5)

array([[0.14907973, 0.1300803 , 0.4587876 , 0.69516722, 0.70229089],
       [0.83771209, 0.00701429, 0.84916905, 0.58741711, 0.58258037],
       [0.34306572, 0.36598778, 0.8942143 , 0.55681433, 0.78625043],
       [0.50373314, 0.46716009, 0.86395075, 0.08259991, 0.4928578 ],
       [0.78363371, 0.51498097, 0.39682537, 0.23603008, 0.73143701]])

In [120]:
np.random.randn(5,5)

array([[ 1.02986442, -1.26140038,  1.80523493, -0.72394485, -2.74344616],
       [-1.7066821 ,  0.22185794,  1.03020679,  0.43926363, -0.84572651],
       [ 0.66705477,  0.37400922, -0.27615839,  0.71557081,  1.40959147],
       [-0.89605499, -3.17878636, -0.11659723,  0.10133658,  0.59825767],
       [-0.52677417,  0.0696449 , -1.14424684, -0.26908015, -0.4614495 ]])

In [122]:
ar=np.random.randint(1,100,10)
print(ar)

[67 20 52 61 56 12 34 19 48 34]


In [125]:
arr=np.arange(25)
runarr=np.random.randint(0,50,10)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [130]:
arr=np.arange(25)
runarr=np.random.randint(0,50,10)
arr.reshape(5,5)
runarr.max()
runarr.argmax()
#argmin and min
#arr.shape()

1

In [138]:
arr=np.arange(25)
runarr=np.random.randint(0,50,10)
arr.reshape(5,5)
runarr.max()
runarr.argmax()
arr.shape
arr.reshape(25,1).shape

(25, 1)

In [139]:
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [140]:
arr=np.arange(0,10)
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [141]:
arr=np.arange(0,10)
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [142]:
arr=np.arange(0,10)
1/arr

C:\Users\dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [143]:
arr=np.arange(0,10)
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [144]:
arr=np.arange(0,10)
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [145]:
np.log(arr)

C:\Users\dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [146]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [147]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [148]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [150]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
arr=np.arange(0,11)
arr
arr[8]

8

In [152]:
arr=np.arange(0,11)
arr
arr[1:5]

array([1, 2, 3, 4])

In [157]:
arr=np.arange(0,11)
arr
arr[0:5]

array([0, 1, 2, 3, 4])

In [155]:
arr=np.arange(0,11)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [160]:
arr=np.zeros(12)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [161]:
arr=np.ones(15)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [166]:
arr[0:10]=5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [179]:
arr=np.arange(5,40)
arr*2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

In [178]:
arr=np.arange(10,80,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

In [ ]:
import numpy as np
import pandas as pd
labels=['a','b','c','d']
my_array=[10,20,30]
pd.Series(data=my_array)